### ISSUE TITLE
info for the GUI

### ISSUE THREAD

**Issue by JM-Bader** [MannLabs/alphapeptstats#159]
![grafik](https://user-images.githubusercontent.com/98888664/229109205-9a2f90e9-8dc1-464a-b383-a8fd61dcc80e.png)

this is not clear to me. 
The tutorial notebook does not touch on the GUI and the example plots shown there appear to be normal jupyter notebook plots, independent from the GUI interface and GUI-generated interactive plots shown on the alphapeptstats landing page

**Comment by elena-krismer** [comment]
You can either use alphapeptstats as 
- `GUI` using the command `alphastats gui` in your terminal (after the pip installation) or  the one-click installer
-  `Python library` shown in the tutorial notebooks and the Documentation

Thanks for bringing this to my attention. I wasn't aware of the fact that the difference wasn't clearly pointed out in the documentation and the readme.  I will update the documentation soon.  💃

**Comment by JM-Bader** [comment]
I want to use it in Python as part of the overall data analysis strategy (also using other tools). 
One key aspect is that I want is that I can use alphapeptstats in python to generate interactive plots. How do I do that?

**Comment by elena-krismer** [comment]
You can follow the tutorial notebooks. Functions like `DataSet.plot_volcano(...)` or `DataSet.plot_pca(...)` will plot an interactive plot (using Plotly). 
The plots in the tutorial notebooks are actually interactive plots, however, the combination GitHub+Plotly+Jupyter Notebook is not working for interactive plots, thus the plots are displayed as static plots on GitHub instead. 
Running the exact same code on your local Jupyter notebook will result in interactive instead of static plots.

**Comment by JM-Bader** [comment]
ok, great!
I suggest you make it explicit on the landing page that there are three levels: 

GUI
python local plot
python github plot

and that based on this level plots can be interactive
